// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleFirst.Infra.Data.Context;

#nullable disable

namespace PeopleFirst.Infra.Data.Migrations
{
    [DbContext(typeof(PeopleFirstDbContext))]
    [Migration("20250421191843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PeopleFirst.Domain.Entities.AvaliacaoColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvaliacaoColaboradorCol")
                        .HasColumnType("longtext")
                        .HasColumnName("avaliacaoColaboradorcol");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int")
                        .HasColumnName("colaborador_id");

                    b.Property<string>("ComentarioGeral")
                        .HasColumnType("longtext")
                        .HasColumnName("comentarioGeral");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<bool?>("Finalizada")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("finalizada");

                    b.Property<int?>("IdColaborador")
                        .HasColumnType("int")
                        .HasColumnName("idColaborador");

                    b.Property<int?>("IdLider")
                        .HasColumnType("int")
                        .HasColumnName("idLider");

                    b.Property<string>("Percepcao")
                        .HasColumnType("longtext")
                        .HasColumnName("percepcao");

                    b.Property<string>("PlanoAcao")
                        .HasColumnType("longtext")
                        .HasColumnName("planoAcao");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("avaliacaocolaborador", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.AvaliacaoColaboradorItemPilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoColaboradorId")
                        .HasColumnType("int")
                        .HasColumnName("avaliacaoColaborador_id");

                    b.Property<int?>("IdAvaliacaoColaborador")
                        .HasColumnType("int")
                        .HasColumnName("idAvaliacaoColaborador");

                    b.Property<int?>("IdItemPilar")
                        .HasColumnType("int")
                        .HasColumnName("idItemPilar");

                    b.Property<int>("ItemPilarId")
                        .HasColumnType("int")
                        .HasColumnName("itemPilar_id");

                    b.Property<decimal?>("Nota")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("nota");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoColaboradorId");

                    b.HasIndex("ItemPilarId");

                    b.ToTable("avalicaocolaboradoritempilar", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.AvaliacaoHealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DominioAgilidadeId")
                        .HasColumnType("int");

                    b.Property<int>("HealthCheckId")
                        .HasColumnType("int");

                    b.Property<decimal?>("NotaFinal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("PilarDominioId")
                        .HasColumnType("int");

                    b.Property<int>("QuestaoPilarId")
                        .HasColumnType("int");

                    b.Property<int>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckId");

                    b.HasIndex("QuestaoPilarId");

                    b.ToTable("AvaliacaoHealthCheck");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext")
                        .HasColumnName("cargo");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("datanascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("longblob")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int")
                        .HasColumnName("idPerfil");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("colaborador", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.DominioAgilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dominio")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DominioAgilidade");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int")
                        .HasColumnName("colaborador_id");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<int>("IdColaborador")
                        .HasColumnType("int")
                        .HasColumnName("idColaborador");

                    b.Property<int>("IdLider")
                        .HasColumnType("int")
                        .HasColumnName("idLider");

                    b.Property<int?>("IdTipoFeedback")
                        .HasColumnType("int")
                        .HasColumnName("idTipoFeedback");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext")
                        .HasColumnName("observacoes");

                    b.Property<string>("Percepcao")
                        .HasColumnType("longtext")
                        .HasColumnName("percepcao");

                    b.Property<string>("PlanoAcao")
                        .HasColumnType("longtext")
                        .HasColumnName("planoAcao");

                    b.Property<int>("TipoFeedbackId")
                        .HasColumnType("int")
                        .HasColumnName("tipoFeedback_id");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("TipoFeedbackId");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.Happiness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvaliacaoGeral")
                        .HasColumnType("longtext")
                        .HasColumnName("avaliacaoGeral");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int")
                        .HasColumnName("colaborador_id");

                    b.Property<int>("ColaboradorPerfilId")
                        .HasColumnType("int")
                        .HasColumnName("colaborador_perfil_id");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<int?>("IdColaborador")
                        .HasColumnType("int")
                        .HasColumnName("idColaborador");

                    b.Property<decimal?>("NotaGeral")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("NotaGeral");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("happiness", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.HealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsideracoesFinais")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdFacilitador")
                        .HasColumnType("int");

                    b.Property<decimal?>("NotaGeral")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("HealthCheck");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.ItemPilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("Item")
                        .HasColumnType("longtext")
                        .HasColumnName("item");

                    b.Property<int>("PilarCompetenciaId")
                        .HasColumnType("int")
                        .HasColumnName("pilarCompetencia_id");

                    b.Property<int?>("PilarCompetenciaId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PilarCompetenciaId");

                    b.HasIndex("PilarCompetenciaId1");

                    b.ToTable("itempilar", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.OpiniaoPilarHappiness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext")
                        .HasColumnName("comentario");

                    b.Property<int>("HappinessId")
                        .HasColumnType("int")
                        .HasColumnName("happiness_id");

                    b.Property<int?>("IdHappiness")
                        .HasColumnType("int")
                        .HasColumnName("idHappiness");

                    b.Property<int?>("IdPilarHappiness")
                        .HasColumnType("int")
                        .HasColumnName("idPilarHappiness");

                    b.Property<decimal?>("Nota")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("nota");

                    b.Property<int>("PilarHappinessId")
                        .HasColumnType("int")
                        .HasColumnName("pilarHappiness_id");

                    b.HasKey("Id");

                    b.HasIndex("HappinessId");

                    b.HasIndex("PilarHappinessId");

                    b.ToTable("OpiniaoPilarHappiness", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PerfilNome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("perfil");

                    b.HasKey("Id");

                    b.ToTable("perfil", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.PilarCompetencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int")
                        .HasColumnName("PerfilId");

                    b.Property<string>("Pilar")
                        .HasColumnType("longtext")
                        .HasColumnName("Pilar");

                    b.Property<int>("TipoCompetenciaId")
                        .HasColumnType("int")
                        .HasColumnName("TipoCompetenciaId");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("TipoCompetenciaId");

                    b.ToTable("PilarCompetencia", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.PilarDominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DominioAgilidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Pilar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DominioAgilidadeId");

                    b.ToTable("PilarDominio");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.PilarHappiness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("DescricaoPilar")
                        .HasColumnType("longtext")
                        .HasColumnName("descricaoPilar");

                    b.Property<string>("Pilar")
                        .HasColumnType("longtext")
                        .HasColumnName("pilar");

                    b.HasKey("Id");

                    b.ToTable("pilarhappiness", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.QuestaoPilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DominioAgilidadeId")
                        .HasColumnType("int");

                    b.Property<int>("PilarDominioId")
                        .HasColumnType("int");

                    b.Property<string>("Questao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PilarDominioId");

                    b.ToTable("QuestaoPilar");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("time", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.TimeColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int")
                        .HasColumnName("colaborador_id");

                    b.Property<int?>("IdColaborador")
                        .HasColumnType("int")
                        .HasColumnName("idColaborador");

                    b.Property<int?>("IdTime")
                        .HasColumnType("int")
                        .HasColumnName("idTime");

                    b.Property<int>("TimeId")
                        .HasColumnType("int")
                        .HasColumnName("time_id");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("TimeId");

                    b.ToTable("timecolaborador", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.TipoCompetencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("tipoCompetencia", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.TipoFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("tipofeedback", (string)null);
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.AvaliacaoColaborador", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.AvaliacaoColaboradorItemPilar", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.AvaliacaoColaborador", "AvaliacaoColaborador")
                        .WithMany()
                        .HasForeignKey("AvaliacaoColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleFirst.Domain.Entities.ItemPilar", "ItemPilar")
                        .WithMany()
                        .HasForeignKey("ItemPilarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvaliacaoColaborador");

                    b.Navigation("ItemPilar");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.AvaliacaoHealthCheck", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.HealthCheck", "HealthCheck")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("HealthCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleFirst.Domain.Entities.QuestaoPilar", "QuestaoPilar")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("QuestaoPilarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCheck");

                    b.Navigation("QuestaoPilar");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.Colaborador", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleFirst.Domain.Entities.TipoFeedback", "TipoFeedback")
                        .WithMany()
                        .HasForeignKey("TipoFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("TipoFeedback");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.Happiness", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.HealthCheck", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.ItemPilar", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.PilarCompetencia", "PilarCompetencia")
                        .WithMany()
                        .HasForeignKey("PilarCompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleFirst.Domain.Entities.PilarCompetencia", null)
                        .WithMany("Itens")
                        .HasForeignKey("PilarCompetenciaId1");

                    b.Navigation("PilarCompetencia");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.OpiniaoPilarHappiness", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.Happiness", "Happiness")
                        .WithMany()
                        .HasForeignKey("HappinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleFirst.Domain.Entities.PilarHappiness", "PilarHappiness")
                        .WithMany()
                        .HasForeignKey("PilarHappinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Happiness");

                    b.Navigation("PilarHappiness");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.PilarCompetencia", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleFirst.Domain.Entities.TipoCompetencia", "TipoCompetencia")
                        .WithMany()
                        .HasForeignKey("TipoCompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("TipoCompetencia");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.PilarDominio", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.DominioAgilidade", "DominioAgilidade")
                        .WithMany("PilarDominios")
                        .HasForeignKey("DominioAgilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DominioAgilidade");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.QuestaoPilar", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.PilarDominio", "PilarDominio")
                        .WithMany("Questoes")
                        .HasForeignKey("PilarDominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PilarDominio");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.TimeColaborador", b =>
                {
                    b.HasOne("PeopleFirst.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeopleFirst.Domain.Entities.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.DominioAgilidade", b =>
                {
                    b.Navigation("PilarDominios");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.HealthCheck", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.PilarCompetencia", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.PilarDominio", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("PeopleFirst.Domain.Entities.QuestaoPilar", b =>
                {
                    b.Navigation("Avaliacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
